name: Continuous Integration

on:
  push:
    branches:
      - main

concurrency:
  group: main
  cancel-in-progress: true

jobs:
  deploy:
    name: Deploy
    runs-on: ubuntu-latest
    steps:
      - name: Configure SSH
        env:
          SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
          SSH_HOST: ${{ secrets.SSH_HOST }}
          SSH_USER: ${{ secrets.SSH_USER }}
        run: |
          mkdir -p ~/.ssh/
          echo "$SSH_PRIVATE_KEY" > ~/.ssh/github
          chmod 600 ~/.ssh/github
          cat >>~/.ssh/config <<END
          Host target
            HostName $SSH_HOST
            User $SSH_USER
            IdentityFile ~/.ssh/github
            LogLevel ERROR
            StrictHostKeyChecking no
          END

      - name: Clone the repository if it doesn't exist
        run: |
          ssh target "if [ ! -d 'django-auth-jwt' ]; then git clone https://github.com/iamhieu2812/django-auth-jwt.git; fi"        
        
        
      - name: Create or update env file in django-auth-jwt
        run: |
          ssh target 'echo "${{ secrets.ENV_FILE }}" > django-auth-jwt/.env'

      - name: Run deploy
        run: |
          ssh target "cd django-auth-jwt/ && docker-compose down && git pull && docker-compose build && docker-compose up -d --force-recreate"

      - name: Run migrate
        run: |
          ssh target "cd django-auth-jwt/ && docker-compose run --rm app manage.py migrate"